# TANGTANG_LIBRARY_HTTP_BEGIN
server {
    listen 80;
    listen [::]:80;
    server_name library.douwuyou.cn;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
        default_type text/plain;
    }

    location / {
        return 308 https://library.douwuyou.cn$request_uri;
    }
}
# TANGTANG_LIBRARY_HTTP_END
